export const countryOptions = [
  { key: 'za', value: 'South Africa', flag: 'za', text: 'South Africa' },
  { key: 'dz', value: 'Algeria', flag: 'dz', text: 'Algeria' },
  { key: 'ao', value: 'Angola', flag: 'ao', text: 'Angola' },
  { key: 'bw', value: 'Botswana', flag: 'bw', text: 'Botswana' },
  { key: 'et', value: 'Ethiopia', flag: 'et', text: 'Ethiopia' },
  { key: 'gh', value: 'Ghana', flag: 'gh', text: 'Ghana' },
  { key: 'ke', value: 'Kenya', flag: 'ke', text: 'Kenya' },
  { key: 'ma', value: 'Morocco', flag: 'ma', text: 'Morocco' },
  { key: 'mz', value: 'Mozambique', flag: 'mz', text: 'Mozambique' },
  { key: 'ng', value: 'Nigeria', flag: 'ng', text: 'Nigeria' },
  { key: 'sz', value: 'Swaziland', flag: 'sz', text: 'Swaziland' },
  { key: 'tz', value: 'Tanzania', flag: 'tz', text: 'Tanzania' },
  { key: 'ug', value: 'Uganda', flag: 'ug', text: 'Uganda' },
  { key: 'zm', value: 'Zambia', flag: 'zm', text: 'Zambia' },
  { key: 'zw', value: 'Zimbabwe', flag: 'zw', text: 'Zimbabwe' },
]

export const cities = [
{value: 'Johannesburg', country: 'South Africa', isProvince: true},
{value: 'Cape Town', country: 'South Africa', isProvince: true},
{value: 'Bhiso', country: 'South Africa', isProvince: true},
{value: 'Bloemfontein', country: 'South Africa', isProvince: true},
{value: 'Nelspruit', country: 'South Africa', isProvince: true},
{value: 'Polokwane', country: 'South Africa', isProvince: true},
{value: 'Kimberly', country: 'South Africa', isProvince: true},
{value: 'Mahikeng', country: 'South Africa', isProvince: true},
{value: 'Pietermaritzburg', country: 'South Africa', isProvince: true},
{value: 'Nairobi', country: 'Kenya', isProvince: false},
{value: 'Mombasa', country: 'Kenya', isProvince: false},
{value: 'Nkuru', country: 'Kenya', isProvince: false},
{value: 'Eldoret', country: 'Kenya', isProvince: false},
{value: 'Kisimu', country: 'Kenya', isProvince: false},
{value: 'Thika', country: 'Kenya', isProvince: false},
{value: 'Kitale', country: 'Kenya', isProvince: false},
{value: 'Malindi', country: 'Kenya', isProvince: false},
{value: 'Garissa', country: 'Kenya', isProvince: false},
{value: 'Kakamega', country: 'Kenya', isProvince: false},
{value: 'Lagos', country: 'Nigeria', isProvince: false},
{value: 'Enugu', country: 'Nigeria', isProvince: false},
{value: 'Owerri', country: 'Nigeria', isProvince: false},
{value: 'Akure', country: 'Nigeria', isProvince: false},
{value: 'Port Harcourt', country: 'Nigeria', isProvince: false},
{value: 'Kaduna', country: 'Nigeria', isProvince: false},
{value: 'Uyo', country: 'Nigeria', isProvince: false},
{value: 'Warri', country: 'Nigeria', isProvince: false},
{value: 'Calabar', country: 'Nigeria', isProvince: false},
{value: 'Dares Salaam', country: 'Tanzania', isProvince: false},
{value: 'Mawanza', country: 'Tanzania', isProvince: false},
{value: 'Arusha', country: 'Tanzania', isProvince: false},
{value: 'Dodoma', country: 'Tanzania', isProvince: false},
{value: 'Mbeya', country: 'Tanzania', isProvince: false},
{value: 'Morogoro', country: 'Tanzania', isProvince: false},
{value: 'Tanga', country: 'Tanzania', isProvince: false},
{value: 'Kahama', country: 'Tanzania', isProvince: false},
{value: 'Tabora', country: 'Tanzania', isProvince: false},
{value: 'Zanzibar City', country: 'Tanzania', isProvince: false},
{value: 'Accra', country: 'Ghana', isProvince: false},
{value: 'Kumasi', country: 'Ghana', isProvince: false},
{value: 'Sakondi-Takoradi', country: 'Ghana', isProvince: false},
{value: 'Sunyani', country: 'Ghana', isProvince: false},
{value: 'Tamale', country: 'Ghana', isProvince: false},
{value: 'Obuasi', country: 'Ghana', isProvince: false},
{value: 'Cape-cost', country: 'Ghana', isProvince: false},
{value: 'Koforidua', country: 'Ghana', isProvince: false},
{value: 'Harare', country: 'Zimbabwe', isProvince: false},
{value: 'Bulwayo', country: 'Zimbabwe', isProvince: false},
{value: 'Mutare', country: 'Zimbabwe', isProvince: false},
{value: 'Chitungwiza', country: 'Zimbabwe', isProvince: false},
{value: 'Epworth', country: 'Zimbabwe', isProvince: false},
{value: 'Gweru', country: 'Zimbabwe', isProvince: false},
{value: 'Kwekwe', country: 'Zimbabwe', isProvince: false},
{value: 'Kadoma', country: 'Zimbabwe', isProvince: false},
{value: 'Masivingo', country: 'Zimbabwe', isProvince: false},
{value: 'Chinhoyi', country: 'Zimbabwe', isProvince: false},
{value: 'Manzini', country: 'Swaziland', isProvince: false},
{value: 'Mbabane, Hlohlo', country: 'Swaziland', isProvince: false},
{value: 'Big Bend, Lubombo', country: 'Swaziland', isProvince: false},
{value: 'Malkerns, Manzin', country: 'Swaziland', isProvince: false},
{value: 'Nhlangano, Shiselweni', country: 'Swaziland', isProvince: false},
{value: 'Siteki, Lumbombo', country: 'Swaziland', isProvince: false},
{value: 'Piggs Peak, Hlohlo', country: 'Swaziland', isProvince: false},
{value: 'Lobamba, Hlohlo', country: 'Swaziland', isProvince: false},
{value: 'Mhlume, Lumbombo', country: 'Swaziland', isProvince: false},
{value: 'Hluti, Shiselweni', country: 'Swaziland', isProvince: false},
{value: 'Kampala', country: 'Uganda', isProvince: false},
{value: 'Entebbe', country: 'Uganda', isProvince: false},
{value: 'Jinja', country: 'Uganda', isProvince: false},
{value: 'Mbale', country: 'Uganda', isProvince: false},
{value: 'Gulu', country: 'Uganda', isProvince: false},
{value: 'Mbarara', country: 'Uganda', isProvince: false},
{value: 'Luanda', country: 'Angola', isProvince: false},
{value: 'Huambo', country: 'Angola', isProvince: false},
{value: 'Lobito', country: 'Angola', isProvince: false},
{value: 'Kuito', country: 'Angola', isProvince: false},
{value: 'Malanje', country: 'Angola', isProvince: false},
{value: 'Benguela', country: 'Angola', isProvince: false},
{value: 'Lucapa', country: 'Angola', isProvince: false},
{value: 'Namibe', country: 'Angola', isProvince: false},
{value: 'Soyo', country: 'Angola', isProvince: false},
{value: 'Lubango', country: 'Angola', isProvince: false},
{value: 'Casablanca', country: 'Morocco', isProvince: false},
{value: 'Fez', country: 'Morocco', isProvince: false},
{value: 'Tangier', country: 'Morocco', isProvince: false},
{value: 'Marrakesh', country: 'Morocco', isProvince: false},
{value: 'Lusaka', country: 'Zambia', isProvince: false},
{value: 'Kitwe', country: 'Zambia', isProvince: false},
{value: 'Chipata', country: 'Zambia', isProvince: false},
{value: 'Ndola', country: 'Zambia', isProvince: false},
{value: 'Kabwe', country: 'Zambia', isProvince: false},
{value: 'Chingola', country: 'Zambia', isProvince: false},
{value: 'Livingstone', country: 'Zambia', isProvince: false},
{value: 'Luanshya', country: 'Zambia', isProvince: false},
{value: 'Mufulira', country: 'Zambia', isProvince: false},
{value: 'Kasama', country: 'Zambia', isProvince: false},
{value: 'Algiers', country: 'Algeria', isProvince: false},
{value: 'Oran', country: 'Algeria', isProvince: false},
{value: 'Blida', country: 'Algeria', isProvince: false},
{value: 'Constantine', country: 'Algeria', isProvince: false},
{value: 'Annaba', country: 'Algeria', isProvince: false},
{value: 'Djelfa', country: 'Algeria', isProvince: false},
{value: 'Biskra', country: 'Algeria', isProvince: false},
{value: 'Batna', country: 'Algeria', isProvince: false},
{value: 'Setif', country: 'Algeria', isProvince: false},
{value: 'Sidi Bel Abbes', country: 'Algeria', isProvince: false},
{value: 'Addis Ababa', country: 'Ethiopia', isProvince: false},
{value: 'Dire Dawa', country: 'Ethiopia', isProvince: false},
{value: 'Mek\'ele', country: 'Ethiopia', isProvince: false},
{value: 'Gondar', country: 'Ethiopia', isProvince: false},
{value: 'Awasa', country: 'Ethiopia', isProvince: false},
{value: 'Dessie', country: 'Ethiopia', isProvince: false},
{value: 'Jimma', country: 'Ethiopia', isProvince: false},
{value: 'Jijiga', country: 'Ethiopia', isProvince: false},
{value: 'Shashamane', country: 'Ethiopia', isProvince: false},
{value: 'Gaborone', country: 'Botswana', isProvince: false},
{value: 'Francistown', country: 'Botswana', isProvince: false},
{value: 'Molepolole', country: 'Botswana', isProvince: false},
{value: 'Selebi-Phikwe', country: 'Botswana', isProvince: false},
{value: 'Maun', country: 'Botswana', isProvince: false},
{value: 'Serowe', country: 'Botswana', isProvince: false},
{value: 'Kanye', country: 'Botswana', isProvince: false},
{value: 'Mahalapye', country: 'Botswana', isProvince: false},
{value: 'Mogoditshane', country: 'Botswana', isProvince: false},
{value: 'Mochudi', country: 'Botswana', isProvince: false},
{value: 'Matola', country: 'Mozambique', isProvince: false},
{value: 'Maputo', country: 'Mozambique', isProvince: false},
{value: 'Nampula', country: 'Mozambique', isProvince: false},
{value: 'Beira', country: 'Mozambique', isProvince: false},
];

export const provinces = [
{value: 'Eastern Cape'},
{value: 'Free State'},
{value: 'Gauteng'},
{value: 'KwaZulu-Natal'},
{value: 'Limpopo'},
{value: 'Mpumalanga'},
{value: 'North West'},
{value: 'Northern'},
{value: 'Western Cape'}
]

export const employment = [
{value: 'Employed'},
{value: 'Unemployed'},
{value: 'Self-Employed'},
{value: 'Currently Studying'},

]

export const income = [
{value: 'I do not earn an income'},
{value: 'Less than R 1000'},
{value: 'R 1000- R10 000'},
{value: 'R10 000- R20 000'},
{value: 'R20 000- R30 000'},
{value: 'R30 000- R60 000'},
{value: 'R60 000+'},
]

export const industry = [
{value: 'Communications/IT Technology'},
{value: 'Agriculture'},
{value: 'Mining'},
{value: 'Manufacturing'},
{value: 'Tourism'},
{value: 'Textile & Apparel'},
{value: 'Wholesale/Retail'},
{value: 'Real Estate Finance & Business Service'},
]

export const education = [
  {text: 'Doctoral Degree, PhD', value:'Doctoral Degree, PhD'},
  {text: 'Masters Degree', value:'Masters Degree'},
  {text: '4-year Degree', value:'4-year Degree'},
  {text:'National Diploma and/or Higher Certificate', value: 'National Diploma and/or Higher Certificate'},
  {text:'Grade 12, Matriculation Exemption NTC 4', value:'Grade 12, Matriculation Exemption NTC 4'},
  {text:'Grade 11, NTC 3', value:'Grade 11, NTC 3'},
  {text:'Grade 10, NTC 2', value:'Grade 10, NTC 2'},
  {text:'Grade 9, School Leaving Certificate, NTC 1, ABET level 4', value: 'Grade 9, School Leaving Certificate, NTC 1, ABET level 4'}
]

export const intrest = [
{text: "Sports (You participate in sports or your're a sports junkie who's always eager for the next football or basketball season)"},
{text: "Travel (You travel often or you follow travel influencers and read travel blogs)"},
{text: "Beauty & Fashion (You are into skincare, make-up and always know about the latest fashion trends)"},
{text: "Fitness (You are a fitness junkie who trains often and enjoy leading a healthy lifestyle)"},
{text: "Entertainment & Media (You want to be a part of the media industry & you follow celebrities, know about new movie releases and the best hang out spots in town)"},
{text: "Finance ( You have interests in financial markets, trading and read publications like FinWeek, CFO Magazine &amp; Financial Mail)"},
{text: "Politics (You are interested in international relations, foreign affairs and follow publications such as Mail & Gaurdian, IOL News)"},
{text: "Technology (You are into IT News, AI, Gagets, BI & Analytics)"},
{text: "Academic"},
{text: "Music"},
{text: "Nutrition"}
]

export const shopping = [
{text: "You like to buy products that are economical and suit your pocket"},
{text: "You are motivated by brand names and always look for guarantees"},
{text: "You are conventional, conservative, unexperimental and buy products based on popularity"},
{text: "You are status conscious and upwarldly mobile"},
{text: "You are brand conscious/loyal and love top of the line products"},
{text: "You're simple, economical and like to pursue a rich inner life"},
{text: "You are conscious of society, social responsibility and want to improve conditions in society"}
]